### ISSUE TITLE
Head not rendering on main menu with MenuMobs

### ISSUE THREAD

**Issue by superbas11** [iwoplaza/MoBends#1]
more info: superbas11/MenuMobs#29

**Comment by iwoplaza** [comment]
![image](https://user-images.githubusercontent.com/7166752/41983975-c1bee72c-7a2f-11e8-85b8-e05637aecba5.png)
This is in fact with Mo' Bends and More Player Models, and seems to be working great in the upcoming release 😄. I consider this issue as closed.

**Comment by Maxwelljones** [comment]
I guess this is still an issue as I am having the same problem:

https://github.com/superbas11/MenuMobs/issues/29

MoBends : 0.24
Menu Mobs: 1.21
Forge: 14.23.5.2768
