### ISSUE TITLE
Elytra animation missing

### ISSUE THREAD

**Issue by Drebledore** [iwoplaza/MoBends#104]
**Is your feature request related to a problem? Please describe.**
I just noticed this while playing with the mod not really a problem :D
The elytra animation is missing on the latest versions, the old 0.24 ver have it.

**Describe the solution you'd like**
Addition of the elytra animation from 0.24 ver

**Describe alternatives you've considered**
I just hid my elytra 

**Additional context**
Hello GoblinBob, I did message you about it before but I figured you forgot about it (cause of irl stuff) so I'm just posting it here. Hopefully you'll see them. btw love the new snapshot you released <3

**Comment by iwoplaza** [comment]
Thanks for reporting this issue, addressing it in the newest snapshow 😄
