### ISSUE TITLE
1.0.0B2 & Ice and Fire - armor bug

### ISSUE THREAD

**Issue by Rekag** [iwoplaza/MoBends#110]
**The bug**
Both variants of the dragonsteel armor from the Ice and Fire mod are bugged with player animations enabled.

**Steps to reproduce the behavior:**
1. Go to any world
2. Make sure that player animations are enabled
3. Put on any of the two dragonsteel armor sets

**Expected behavior**
The armor should bug out, mainly the chestplate which should disappear completely, along with the boots, as seen in the images attached.
**not shown in the images** - after the bug occurs, armor will further bug out when the player tries to take it off and put it on again, then the helmet will not appear at all until the game is restarted.

**screenshots**
with player animations disabled (R) and enabled (L)

![1](https://user-images.githubusercontent.com/67206172/85218368-efa29800-b399-11ea-8f3f-b830e3193cec.png)

![2](https://user-images.githubusercontent.com/67206172/85218371-f0d3c500-b399-11ea-911a-bf0b3eda5ab4.png)

**Context:**
 - Minecraft version: 1.12.2
 - Mo' Bends version: 1.0.0-beta-2
 - additional mods:
  - Optifine HD U E3
  - Ice and Fire 1.9.1
- Forge version: 14.23.5.2847

**Comment by Terra-B-Welch** [comment]
Also occurs with Alpha Yeti armor from Twilight Forest.

It seems to be with armor that use the same render layer as the player's skin.

**Comment by LePizzaRabbit** [comment]
exact smae problem

**Comment by iwoplaza** [comment]
Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.

**Comment by Terra-B-Welch** [comment]
> 
> 
> Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.



Whats the list on the out of the box support?

**Comment by iwoplaza** [comment]
> > Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.
> 
> Whats the list on the out of the box support?

Haven't tested the other mods yet. By out-of-the-box I mean that the system is quite generic, and should work properly if the armor model is reasonably constructed. The extent of the compatibility will get tested throughout this weekend.
