### ISSUE TITLE
2 Heads Error?

### ISSUE THREAD

**Issue by CarIG1** [iwoplaza/MoBends#114]
Hello! I am having an error where I get 2 heads and an extra pair of arms! It even shows up like that in my inventory and whenever I change perspectives, it stays the same. Any fixes for this? Here are the mods I have: 
![modlist](https://user-images.githubusercontent.com/67566388/85964112-40535b80-b96d-11ea-85c5-64d3c58abfb7.PNG)

![Screenshot (32)](https://user-images.githubusercontent.com/67566388/85964014-e2267880-b96c-11ea-8589-168f955e67f4.png)
![Screenshot (31)](https://user-images.githubusercontent.com/67566388/85964016-e783c300-b96c-11ea-89f3-59a8c43b8a0f.png)
![Screenshot (30)](https://user-images.githubusercontent.com/67566388/85964022-ebafe080-b96c-11ea-84ad-ef511204b3e0.png)

**Comment by verneLX** [comment]
You have to remove MW mod for it to work.
Your Wellcome.

**Comment by Vulant** [comment]
If you update Mo'Bends to the latest version, you won't get double heads
