### ISSUE TITLE
Multiple player models showing at once

### ISSUE THREAD

**Issue by StrangeTaniwha** [iwoplaza/MoBends#116]
When in third person, and in the inventory, you can see multiple player models (maybe 3 exactly). One is normal (animations running fine) , one is slightly above the other (also using mod animations), and one is completely unanimated and still. This problem doesn't affect gameplay in first-person view. If there's anything I can do to fix this, I'd appreciate the help.

![20200704_020135](https://user-images.githubusercontent.com/67819174/86507029-7ee87c00-bd9a-11ea-8f9c-fc88abe9b3f4.jpg)
![20200704_020144](https://user-images.githubusercontent.com/67819174/86507033-827c0300-bd9a-11ea-9713-4130add20831.jpg)
![20200704_020152](https://user-images.githubusercontent.com/67819174/86507034-84de5d00-bd9a-11ea-8a7e-c7f4fad5ae4d.jpg)

 - Minecraft version: 1.12.2, Forge 14.23.5.2847
 - Mo' Bends version: 0.24
 - Other installed mods
![20200704_020205](https://user-images.githubusercontent.com/67819174/86507036-8ad43e00-bd9a-11ea-93ba-462f856cdb04.jpg)

**Comment by iwoplaza** [comment]
0.24 is an outdated version of Mo' Bends, update it from the CurseForge site to 1.0.0 BETA :smile:.
