### ISSUE TITLE
Config for classifying "bow/gun" items to point forwards.

### ISSUE THREAD

**Issue by Raven-Six** [iwoplaza/MoBends#118]
As per request, a suggestion on discord was posted about creating a wider compatibility with MoBends and a larger range of mods. 

At the moment, mods such as flan's mod, Vic's Modern Warfare, and techguns have an issue with MoBends where firearms are pointed incorrectly towards the ground.

A simple solution to this, similar to the sword whitelist in the config is to add another whitelist for held items that are needed to be pointed towards the cursor which can also easily solve compatibility issues with many other mods and most commonly for mods that add in firearms.

Attached is the original suggestion from discord.
![image](https://user-images.githubusercontent.com/68027630/86956230-02e19180-c116-11ea-9859-42a48d9c311d.png)

**Comment by rvveber** [comment]
Bumping this!
We really need this for flans please!

@iwoplaza

**Comment by iwoplaza** [comment]
The bow aiming animation is now straight forward by default. That should fix the problem universally 😄
