### ISSUE TITLE
The character leans when walking

### ISSUE THREAD

**Issue by ColaLiao** [iwoplaza/MoBends#132]
The character leans when walking

view from other player,
or open inventory when walking.

 - Minecraft version: Forge 2847
 - MoBends_1.12.2-1.0.0-beta-20.06.20.jar

**Comment by forresthopkinsa** [comment]
You can also see it from F5 third-person view

**Comment by iwoplaza** [comment]
This has been adressed, and a fix for this will be rolled out with the upcoming BETA-3 version.
