### ISSUE TITLE
Bug Animation with Modern Warfare

### ISSUE THREAD

**Issue by ghost** [iwoplaza/MoBends#137]
**Describe the bug**
When I able the player animation (via your menu) and I use certain weapon from modernwarfare, mods becames incompatible Modern Warfare has their animation becam buggued

**To Reproduce**
1. install MW warfare
2. take weapon
3. some bug placement in animation and tpp animation disable

**Expected behavior**
when I disable the animation it stop

**Context (please complete the following information):**
 - Minecraft version: [1.12.2]
 - Mo' Bends version [1.0.0-beta]
 - Other installed mods [MW Warfare]

**Additional context**
An work around could be to disable your annimation when using certain Items from mod (specify in config), or disable certain animation when using mw item (tpp or fpp) or maybe do some compatibility thing

**Comment by iwoplaza** [comment]
Thanks for the report! Let's continue discussion in #201
