### ISSUE TITLE
'Duplicate player' glitch

### ISSUE THREAD

**Issue by XiaoBao13** [iwoplaza/MoBends#146]
This "duplicate player" glitch, is a glitch to where it would add the top half of your character while animated still like the original. It still has armor and its hat. Also the hat on the original character is stuck in place and wont animate with your character.

**To Reproduce**
1. Go to Single player
2. Click on any world or create a new one.
4. Press F5 or whatever your third person button is.

**Expected behavior**
The normal animation of the player and the character animated, but still the same.

**Screenshots**
[http://www.mediafire.com/view/yyqtj0wzc3owsj7/Screenshot_2160.png/file]

**Context (please complete the following information):**
 - Minecraft version:  1.12.2
 - Mo' Bends version 0.24
 - Other installed mods Optifine, music player, Creative core, Thicc entities. enhanced visuals, ichunutil, mob dismemberment, wastelands, u team core, vics modern warfare, custom starting gear.

**Comment by ivydudzik** [comment]
this is still very much an issue. can we expect an eta on a resolution?

**Comment by iwoplaza** [comment]
I've never encountered the problem during play with just Mo' Bends 1.0.0-beta installed. Does this still happen on the latest 1.0.0-beta release?

**Comment by ivydudzik** [comment]
absolutely my fault. i was using an outdated version of the mod because i usually stick to releases and stay away from betas. i shouldve checked before posting. my bad!!

**Comment by color-space** [comment]
Please close the issue than. @deandudzik.
