### ISSUE TITLE
please add to 1.16.4 it would be awsome

### ISSUE THREAD

**Issue by dragonsama2414** [iwoplaza/MoBends#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EspadaEsteban** [comment]
the creators said they would add the mod to 1.16.4 when version 1.0.0 comes out for 1.12.2.

**Comment by iwoplaza** [comment]
There's a whole project board dedicated to porting Mo' Bends to 1.16.x, no need to keep track of this issue 😄
