### ISSUE TITLE
Cant uninstall in server/client

### ISSUE THREAD

**Issue by Kiba9615** [iwoplaza/MoBends#168]
I use tlauncher, I add mo bends and many other mods, also added to my server in athernos, I wan to uninstall this mod, but when I removed it, I inter to the server, open my inventory, the game crashes, Anyone how to uninstall without crashes? I'm using Minecraft 1.12.2 and the mo bends 1.0.0 beta 2, forge 1.23.5.2854, and optifine 1.12.2 HD U f4
Those are the mods that I'm using in the servers/client 
Damage indicators 3.5.1
armory expansion  1.4.2
astral sorcery 1.10.27
astrological sorcery 1.1.3
Baubles 1.5.2
better animal plus 9.0.1
chameleon 4.1.3
clearlag
conarmd 1.5.9
ctm mc 1.0.2.31
dynamic trees 0.9.21
electroblobs 4.3.1
elevator mod 1.3.14
forglein1.4.8
future mc 0.2.4.1
galacticraft core 4.0.2.281
galacticraft planes 4.0.2.81
iceandfire 1.9.1
jei 4.16.1.301
journey map 5.7.1
libnine 1.2.0
library 1.7.19
mantle 1.3.3.55
micdoodlecore 4.0.2.281
moreplanets 2.1.14 gc261
mowziesmob 1.5.4
multimob 1.0.5
patchouli 1.0 22
primitivemobs 1.2.3a
stevekungslib 1.1.19
storage drawers 5.4.2
tconevo 1.0.38
tconstruct 2.13.0.183
tinkers complement 0.4.3
tombstone 4.0.1
toroquest 5.3
travelers backpack 1.0.34
twilight forest 3.11.1021

**Comment by iwoplaza** [comment]
Mo' Bends doesn't change anything that could cause this bug, it doesn't really have any features on the server apart from security configs. This has to be caused by another mod. If you're sure it's Mo' Bends, I'd like to see the crash report to investigate further on what happened 😄
