### ISSUE TITLE
A crash report

### ISSUE THREAD

**Issue by 834297926** [iwoplaza/MoBends#17]
---- Minecraft Crash Report ----
// I blame GoblinBob, author of Mo' Bends.

Time: 2018-07-19 11:40:21 CST
Description: Unexpected error

java.lang.NullPointerException
    at net.gobbob.mobends.client.event.DataUpdateHandler.onClientTick(DataUpdateHandler.java:53)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_DataUpdateHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1706)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4438)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 0 total; []
  Chunk stats: MultiplayerChunkCache: 0, 0
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 0 total; []
  Retry entities: 0 total; []
  Server brand: ~~ERROR~~ NullPointerException: null
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (x86) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
  Memory: 479106416 bytes (456 MB) / 872415232 bytes (832 MB) up to 1073741824 bytes (1024 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
  IntCache: cache: 0, tcache: 82, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.4.2738 9 mods loaded, 9 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID              | Version                      | Source                        | Signature                                |
       |:------ |:--------------- |:---------------------------- |:----------------------------- |:---------------------------------------- |
       | UCHIJA | minecraft       | 1.12.2                       | minecraft.jar                 | None                                     |
       | UCHIJA | mcp             | 9.42                         | minecraft.jar                 | None                                     |
       | UCHIJA | FML             | 8.0.99.99                    | forge-1.12.2-14.23.4.2738.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJA | forge           | 14.23.4.2738                 | forge-1.12.2-14.23.4.2738.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJA | inventorytweaks | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJA | journeymap      | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar   | None                                     |
       | UCHIJA | mobends         | 0.24                         | mobends-0.24_for_MC-1.12.jar  | None                                     |
       | UCHIJA | quickget        | 1.0                          | quickget-1.0.jar              | None                                     |
       | UCHIJA | vanillafix      | 1.0.9-97                     | VanillaFix-1.0.9-97.jar       | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
  GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3262' Renderer: 'Intel(R) HD Graphics'
  Suspected Mods: Mo' Bends (mobends)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics GL version 4.2.0 - Build 10.18.10.3262, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: ç®€ä½“ä¸­æ–‡ (ä¸­å›½)
  Profiler Position: N/A (disabled)
  CPU: 2x Intel(R) Pentium(R) CPU G3260 @ 3.30GHz
  Client Crashes Since Restart: 3
  Integrated Server Crashes Since Restart: 0

**Comment by iwoplaza** [comment]
Should be fixed in the upcoming 1.0.0 version of Mo' Bends 🙂
