### ISSUE TITLE
1.12.2 Construct's Armory "support"

### ISSUE THREAD

**Issue by cloby0** [iwoplaza/MoBends#173]
I have Construct's Armory and Mo' Bends on and whenever I equip a ConArm armor all the arm armor is on my left arm and my boots are behind my feet. The helmet is fine but every thing else is screwed. I don't know if this qualifies as custom animations because I don't make mods. I didn't know to report this as a Mo' Bends bug or a ConArm bug so I'm going to post this on both of them.

**Comment by iwoplaza** [comment]
Thank you for the report! Let's continue discussion in this thread #196
