### ISSUE TITLE
Tinker's Armory bug

### ISSUE THREAD

**Issue by snottytoe69** [iwoplaza/MoBends#183]
**Describe the bug**
When equipping any armor from the mod Constructs Armory, the armor addon for Tinker's construct, the armor does not fit the character properly and stays flat towards the camera (when looking straight up, the legs and boots of the armor will be away from the player and the chest piece will be facing towards the sky.

**To Reproduce**
1. equip any armor added by constructs Armory

**Expected behavior**
I very much expected the armor to fit properly onto the player, but got the bug instead.

**Screenshots**
You can see the way the armor stays on a pivot basically, always facing the same direction towards the camera
![image](https://user-images.githubusercontent.com/62779309/105802535-fc572200-5f60-11eb-9ac4-800184992dda.png)

**Context (please complete the following information):**
 - 1.12.2
 -  1.0.0-beta
 - Just optifine. Bug appeared in a mod pack, however when launching just the two culprits, the bug still persisted.

**Additional context**
Not exactly game breaking, but can get a bit annoying. Also the player sprite in the UI of the armory forge table jitters alot.

**Comment by iwoplaza** [comment]
Thanks for the additional screenshots and description. Let's continue discussion here #196
