### ISSUE TITLE
glitched model

### ISSUE THREAD

**Issue by SwegPepe** [iwoplaza/MoBends#19]
![image](https://user-images.githubusercontent.com/41531784/43042356-53f4e8f4-8d30-11e8-967c-0fc210131c33.png)
does anyone know what might be causing this?

**Comment by InSimpleTermsJordan** [comment]
Looks like it's using an Alex-style texture (3px-wide arms) on a Steve-style model (4px-wide arms). Probably use a different skin or switch player models.

**Comment by iwoplaza** [comment]
This has been fixed in the upcoming 1.0.0 version of Mo' Bends 🙂
