### ISSUE TITLE
Gun F5 animation

### ISSUE THREAD

**Issue by JuniorzGT** [iwoplaza/MoBends#192]
Ive wanted to use tech guns with this animation but when i use 2nd person or 3rd person theres is no gun animation like you holding a gun its just your hand down holding a gun like a normal item, please fix this asap i wanted to make an animation but because of this i cant

**Comment by iwoplaza** [comment]
Hey! Since this is a question about adding custom animations for mods, I'll refer further discussion to this thread #234
