### ISSUE TITLE
Player animatings when fly on dragons(Ice and Fire mod) 

### ISSUE THREAD

**Issue by Skyere** [iwoplaza/MoBends#193]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.12.2]
 - Mo' Bends version [e.g. 1.0.0, 1.0.0-beta]
 - Other installed mods [e.g. Optifine]

**Additional context**

**Comment by iwoplaza** [comment]
Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.
