### ISSUE TITLE
Mo' Bends and Constuct's Armory.

### ISSUE THREAD

**Issue by WaffleyAero** [iwoplaza/MoBends#196]
Hello Mo' Bends Mod Owner. You See I Found Likely A Bug/Needed Feature :D  You See The Image's Show That Armor Is Not Good Like Normal Vanilla Like Diamond, Iron Etc. Etc.. So Please Make A Feature That This Mod Can Work With Construct's Armory. Thank Yoy. (It glitches a lot). (I hope you update to 1.16.5 soon :D )   (EDIT Also fix it with "IronMan" Mod and it's addons. Thank You).

![image](https://user-images.githubusercontent.com/77974116/109141749-c0cd9480-7766-11eb-9458-e523171a0460.png)
![image](https://user-images.githubusercontent.com/77974116/109141755-c3c88500-7766-11eb-9a9f-96eaa36d4c75.png)
![image](https://user-images.githubusercontent.com/77974116/109141767-c75c0c00-7766-11eb-9a3c-8e538110fdc6.png)
![image](https://user-images.githubusercontent.com/77974116/109141779-c925cf80-7766-11eb-87ea-e6925e1bd839.png)
![image](https://user-images.githubusercontent.com/77974116/109141782-cb882980-7766-11eb-970e-ba3dbf87c42e.png)
![image](https://user-images.githubusercontent.com/77974116/109141789-cd51ed00-7766-11eb-9603-ef6f3ddf4e0a.png)

Last One Is Glitching Like Move Glitching 
![image](https://user-images.githubusercontent.com/77974116/109141828-d80c8200-7766-11eb-91d2-da5a1c45111c.png)

Also I Want To Give You A Crash Report Because Ff Mod "LuCraft" About SuperHeroes
Crash:

[crash-2021-02-26_14.14.18-client.txt](https://github.com/mobends/MoBends/files/6049568/crash-2021-02-26_14.14.18-client.txt)

**Comment by TheComputerizer** [comment]
I can second the armor animation issues with construct's armory

**Comment by WaffleyAero** [comment]
> I can second the armor animation issues with construct's armory

The thing is. That i get armor on when having "Mo' Bends" Mod on with "Construct's Armory".

**Comment by TheComputerizer** [comment]
Yes, this is the mo bends issues page

**Comment by WaffleyAero** [comment]
...

**Comment by WaffleyAero** [comment]
I.... I can't. I'm saying that mo' bends and constrcut's armory aren't working well together man. DO YOU UNDERSTAND?

**Comment by TheComputerizer** [comment]
Yes, that is what I was agreeing with

**Comment by iwoplaza** [comment]
Language barrier issues, you gotta love it, haha. Thanks for the report! I'll look into it.

**Comment by iwoplaza** [comment]
Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.

**Comment by pentapox** [comment]
Hey, just making sure since I'm new to all this minecraft modding. This update to fix the compatibility issues with armor mods will be released for 1.12.2 users, right?

**Comment by pentapox** [comment]
Also, great work on your mod. This one's amazing.

**Comment by Spitfire421** [comment]
Great job with the newest 1.12 update. Seems like the compatibility with modded armors (Tinkers in particular) still has some bugs. The armors aren't syncing with the movements of the character.

**Comment by TheComputerizer** [comment]
I can also attest to this. Tinker's armor is no longer sideways like it was before, but it still follows the movements of the vanilla animation

**Comment by XENOR31000** [comment]
yep still using vanilla animations with the tinker armory

**Comment by papuSpartan** [comment]
Any update on this for 1.12.2? Would love to see armors in sync with these animations.

**Comment by PZalacain** [comment]
Ice&Fire armors looks OK, but ConstructArmory is not fixed. Still on development?
