### ISSUE TITLE
Thaumcraft 6 Fortress Armor 

### ISSUE THREAD

**Issue by Exemplus** [iwoplaza/MoBends#198]
**Describe the bug**
When my character wears the Thaumcraft Fortress armor it doesn't have the right textures. He doesn't look like he's wearing the armor, bits and pieces show glitched on the skin. See screenshots for a better description.
**To Reproduce**
1. Equip the Thaumcraft 6 Fortress armor (any and all pieces separate or together) and look at yourself with f5 or your inventory preview.

**Expected behavior**
I expected the armor to look how it normally does without this mod but with the Mobends animations and the such.

**Screenshots**
![2021-03-12_17 26 55](https://user-images.githubusercontent.com/80553666/111011962-71878680-8358-11eb-8777-2bb813b4bd69.png)
![2021-03-12_17 26 58](https://user-images.githubusercontent.com/80553666/111011963-72b8b380-8358-11eb-9b6f-35d9de47b2f8.png)
![2021-03-12_17 27 04](https://user-images.githubusercontent.com/80553666/111011966-73514a00-8358-11eb-8e07-d61de59082b9.png)
![2021-03-12_17 27 23](https://user-images.githubusercontent.com/80553666/111011968-73e9e080-8358-11eb-9c91-e528947559e8.png)

**Context (please complete the following information):**
 - Minecraft version: 1.12.2
 - Mo' Bends version 0.24
 - Other installed mods:
  
Applied Energistics2
Aroma1997Core
Aroma1997s-Dimensional-World
backpack
Baubles
buildcraft
ChickenChunks
CodeChickenLib
CoFHCore
CoFHWorld
colytra
EnderStorage
energyconverters
Forelin
ForgeMultipart
FullscreenWindowed
gravestone
Hwyla
industrialforegoing
infiintemusic
inronchest
jei
mcjtylib
millenaire
MrTJPCore
NotEnoughItems
ProjectRed
ProjectRed
RedstoneFlux
rftools
subcommonlib-sublib
telepads
tesla-core-lib
Thaumcraft
ThermalDynamics
ThermalExpansion
ThermalFoundation
Xaeros_Minimap
 
**Additional context**
Just that if you need versions for the mods above I can give those to you. This is my first time posting about a problem so if I need to clarify anything let me know.

**Comment by Exemplus** [comment]
I should add that it is supposed to look like this:
![image](https://user-images.githubusercontent.com/80553666/111012701-2a9a9080-835a-11eb-91dd-3c6a9dd119e9.png)

**Comment by NinjaKiller77** [comment]
im pretty sure the bends are the issue here, cause the bends might be messing with the textures
but idk im not a bug expert

**Comment by iwoplaza** [comment]
![image](https://user-images.githubusercontent.com/7166752/128644162-c7033687-b888-4e41-8180-eede546d9029.png)

This issue has been addressed. It seems to work perfectly now! This fix will be rolled out in the upcoming BETA-3 update.
Thanks for the report!
