### ISSUE TITLE
does this work with fisk?

### ISSUE THREAD

**Issue by SonNub** [iwoplaza/MoBends#199]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.12.2]
 - Mo' Bends version [e.g. 1.0.0, 1.0.0-beta]
 - Other installed mods [e.g. Optifine]

**Additional context**

**Comment by iwoplaza** [comment]
Please provide actual bugs and screenshots of how those bugs look/behave, and how you think it should behave.
