### ISSUE TITLE
Armor clipping 

### ISSUE THREAD

**Issue by Dhrkness** [iwoplaza/MoBends#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.12.2]
 - Mo' Bends version [e.g. 1.0.0, 1.0.0-beta]
 - Other installed mods [e.g. Optifine]

**Additional context**
Armor is clipping through the player and is not animated with the player model

**Comment by iwoplaza** [comment]
No screenshots, don't really know what's happening. Closing this issue for now.
