### ISSUE TITLE
Armor animation missing

### ISSUE THREAD

**Issue by maumerm** [iwoplaza/MoBends#214]
![Screenshot 2021-04-26 044403](https://user-images.githubusercontent.com/83214344/116063081-27c5d780-a64a-11eb-870c-4714dd7dd51f.png)

**Comment by iwoplaza** [comment]
Closing for reason of insufficient details. I'm guessing this is a problem with using Vic's Modern Warfare mod and if so, there's already an issue for that #201. If not, please create another issue with more detail. Refer to the issue template.
