### ISSUE TITLE
Armor texture issue

### ISSUE THREAD

**Issue by EnriqueNM23** [iwoplaza/MoBends#215]
**Describe the bug**
When you equip armor, some of the arm texture disappears.

**To Reproduce**
1. Equip and armor
2. Change view to thirdperson
3. See incomplete texture 

**Expected behavior**
The armor texture should completely cover the arm.

**Screenshots**
[Animations On](https://i.imgur.com/aDXsBEP.png)
[Animations Off](https://i.imgur.com/028n140.png)

**Context**
 - Minecraft version: 1.12.2
 - Mo' Bends version: 1.0.0/1.0.0-beta
 - Other installed mods: None

**Additional context**
The armor texture is from a texture pack (Conquest).

**Comment by iwoplaza** [comment]
This has been addressed, the fix for this will be rolled out with the upcoming BETA-3 release. Thanks for the report!
