### ISSUE TITLE
Tongue bug on baby wolf

### ISSUE THREAD

**Issue by Samlegamer** [iwoplaza/MoBends#217]
Hello I recently used Mo Bends to see the animations it offered.
I reproduced 2 wolves to have a 3rd one and I noticed that the animation texture of the baby wolf's tongue was too big for its size, and that there was also a bug in its feet .

**Comment by iwoplaza** [comment]
This issue has been fixed and will be rolled out in the upcoming BETA-3 update.
![image](https://user-images.githubusercontent.com/7166752/129389531-784a0bb4-d2a9-4a6c-b899-dfa81e1dd793.png)
