### ISSUE TITLE
The animations are messed up, and still there even if i delete the mod

### ISSUE THREAD

**Issue by Destructor25** [iwoplaza/MoBends#219]
**Describe the bug**
The mod is acting weird, like the sword and swimming animations dont work properly by example

**To Reproduce**
i honestly think its by another mod i put in, but i cant think of any that would damage the mod

**Expected behavior**
To the animations to be normal like intended

**Screenshots**

**Context (please complete the following information):**
 - Minecraft version: 1.12.2
 - Mo' Bends version 1.0.0 beta 20.06.20
 - Other installed mods: (in one of the screenshots)

**Additional context**
The messed up animations were still there, even if i turned off the mod or deleted it
![error 1](https://user-images.githubusercontent.com/84213488/118381614-2a18b300-b5b2-11eb-82f7-1ea71ceab152.PNG)
![error 2](https://user-images.githubusercontent.com/84213488/118381618-313fc100-b5b2-11eb-921e-c3563dd1fe16.PNG)
![mods](https://user-images.githubusercontent.com/84213488/118381622-3d2b8300-b5b2-11eb-855e-143f1a50b315.PNG)

**Comment by iwoplaza** [comment]
All I could suggest is to try to move the mods outside of the `mods/` folder to see if that fixes the issue, and then put the mods back in gradually to find the culprit.
