### ISSUE TITLE
Mobends

### ISSUE THREAD

**Issue by RomankaBuhanka** [iwoplaza/MoBends#222]
Hello, i see a bug with armor textures, can you fix this plaese?

**To Reproduce**
1. nothing
2. nothing
3. nothing
4. textures are glitching

**Expected behavior**
I want normal textures,
![2021-06-08_17 32 47](https://user-images.githubusercontent.com/85567803/121205752-99678700-c880-11eb-9826-82759fbb1212.png)
![2021-06-08_17 32 51](https://user-images.githubusercontent.com/85567803/121205758-9a001d80-c880-11eb-9ce1-3512ea151366.png)
![2021-06-08_17 34 18](https://user-images.githubusercontent.com/85567803/121205761-9a98b400-c880-11eb-9ec2-0c4a3e8496db.png)
![2021-06-08_17 34 20](https://user-images.githubusercontent.com/85567803/121205764-9a98b400-c880-11eb-8ac7-3f5139911a41.png)

 please fix this)))

**Screenshots**
If appl
![2021-06-08_17 32 51](https://user-images.githubusercontent.com/85567803/121204818-d7b07680-c87f-11eb-986d-8d6f5a3251ab.png)

![2021-06-08_17 34 20](https://user-images.githubusercontent.com/85567803/121205061-07f81500-c880-11eb-8a42-1a9c4760b505.png)

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.12.2]
 

**Additional context**
the  problem with all 3-D model textures of armor from all mods on minecraft version 1.12.2

**Comment by RomankaBuhanka** [comment]
Please, fix glitching of armor)))
This mod called ICE AND FIRE.
I found this problem in ALL mods with 3-D model armor textures.

**Comment by RomankaBuhanka** [comment]
The GLITCHING texture in UP BELOW.
the NORMAL texture in DOWN BELOW.

**Comment by NovaLynxie** [comment]
Identical visual bug to #42 which was reported some time ago. Mod is still in development so this may take some time to fix.

**Comment by RomankaBuhanka** [comment]
Thanks for warming

ср, 16 черв. 2021, 17:17 користувач Macky Fitz ***@***.***>
пише:

**Comment by iwoplaza** [comment]
Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.
