### ISSUE TITLE
Inventory Model Bug

### ISSUE THREAD

**Issue by NathanCPlaster** [iwoplaza/MoBends#224]
I am using Mo Bends 1.12.2-4.16.1.301.jar for minecraft 1.12.2.  I am also running several other mods but mo bends is the only movement based mod.  I can provide the list if need be.  When placing a torch (and only a torch) into the left hand slot, the arm sticks out backwards from the player while in the inventory screen.  I am using Optifine 1.12.2_HD_U_G5.jar.  You can see the arm backwards while in the inventory screen, different pov is not affected.

**Comment by iwoplaza** [comment]
This bug fix is rolling out later this week. Thanks for the report!
