### ISSUE TITLE
Wings mod 1.12.2 compatibility for 1.0.0-beta

### ISSUE THREAD

**Issue by lukanin12** [iwoplaza/MoBends#227]
In 0.24 (for Minecraft 1.12 mod) wings from Wings mod wiggle and move with player's body's animation. 
(AIM with bow) + shift = connected wings
![Снимок экрана (432)](https://user-images.githubusercontent.com/62360873/124163348-32687700-daa8-11eb-8772-24d69cf3aa70.png)

In 1.0.0-BETA-2 wings lose their animations.
(AIM with bow) = wings separated from body
![Снимок экрана (433)](https://user-images.githubusercontent.com/62360873/124163825-ab67ce80-daa8-11eb-98c2-96e721aa118c.png)

shift = wings separated from body
![Снимок экрана (434)](https://user-images.githubusercontent.com/62360873/124164038-fa156880-daa8-11eb-9fda-e729f3eb76e8.png)

Mods on Minecraft version: [1.12.2]:
  - Mo' Bends version [1.0.0-beta]
 - Wings [1.1.6]
 - Optifine

**Comment by iwoplaza** [comment]
Okay, what are the Wings in the Wings mod? Are they an armor piece? If so, then that would kinda make sense. The new beta introduced a new system for mutating custom armors.

A temporary solution right now would be to add the armor items to a list of armors that should be kept as vanilla (in the mod's config).

**Comment by Zackonark** [comment]
Wings also grants the play flight, but mo' bends at default plays a falling animation when flying with wings. Dunno if this has been said as I only just found this issue and am currently researching my configuration options. I will say tho that the wiki says I can get the default bends pack from the mod's menu, but mine doesn't show up from what I can tell

**Comment by iwoplaza** [comment]
Refer to #254 for further conversation.
