### ISSUE TITLE
Animation Support to Custom Npc

### ISSUE THREAD

**Issue by Agostinho-Eduardo** [iwoplaza/MoBends#228]
Some mods don't have the animations in or they cant port the animations so if you put port system that every mod can adapt into his own code, mods like custom npcs, the npcs animations are like the player ones, so the animations would be the same as the player ones, i know that can be difficult but this is my suggestion

**Comment by iwoplaza** [comment]
Thanks for the suggestions! I explain how custom animations (including other mod animations) could be and probably will get solved in future versions of Mo' Bends here #234.
