### ISSUE TITLE
(for the future 1.16.5)perhaps the idea has already been proposed,but I would like to suggest that when crawling on the ground there would be its own animation (good luck)

### ISSUE THREAD

**Issue by hail08** [iwoplaza/MoBends#229]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iwoplaza** [comment]
All animations will get addressed once I get to animating the player character. That won't happen until I finish making new animation tools. Thank you for reminding me though! 😄
