### ISSUE TITLE
Player/camera shake and levitating when I enable a pack.

### ISSUE THREAD

**Issue by ElRedstoniano** [iwoplaza/MoBends#23]
I'm a begginer of this mod (and also I'm not english, so sorry for possible grammar/vocab. errors), When I opened the menu and then I enabled a pack (without nothing), the player camera began to shake when I'm on ground. Also, when I fly, the player levitates up without doing anything, players can jump like the double as the normal and also walking and running speed is a little slow as it should be. (Important: I'm not using any mod, only optifine. And also, I'm using the 0.24 version for 1.12). If there's any solution for this issue, or it's just a bug, notice me. Thanks for reading.

**Comment by deltanedas** [comment]
Save and exit, then enter the world again. It's annoying but comes with an easy fix.

**Comment by MineThingIssues** [comment]
I actually found this to be an issue with optifine compatability. After installing the latest version of forge and optifine and mobends I finally got the issue to be fixed

**Comment by deltanedas** [comment]
Nice, someone close.

**Comment by iwoplaza** [comment]
This was actually a long-running bug in Mo' Bends, but it's been fixed in the upcoming 1.0.0 version 🙂
