### ISSUE TITLE
Unaddressed Issues with 3D Armors rendering incorrectly.

### ISSUE THREAD

**Issue by ghost** [iwoplaza/MoBends#230]
**Describe the bug**
When wearing other mod's 3d armors, there's a chance they start rendering incorrectly. I'm not sure what causes it to start, as it's not always present. The armor renders completely incorrectly, often hovering inches off of the player.

**To Reproduce**
1. Install Ice and Fire 
2. Wear Troll armor or Dragon Armor
3. Watch as the armor sometimes doesn't render properly??

**Comment by iwoplaza** [comment]
Most custom armors, including armors from Ice & Fire: Dragons are now compatible out of the box, which will get released with BETA-3.

**Comment by ghost** [comment]
Please consider offering support for TheBetweenlands Volarkit glider!

**Comment by iwoplaza** [comment]
> Please consider offering support for TheBetweenlands Volarkit glider!

This doesn't seem to be an Ice & Fire: Dragons compatibility problem. If you have an enhancement proposition, consider starting a new issue that shows how the current Mo' Bends version behaves with the **TheBetweenlands Volarkit glider** item.
Thanks!
