### ISSUE TITLE
Custom animation

### ISSUE THREAD

**Issue by asanginxst** [iwoplaza/MoBends#231]
Can players customize the original monster and Steve's animation player?
Example: I installed the Spartan weapon. When I hold the two-handed giant sword of the Spartan weapon, I don’t want Steve to swing it with one hand. At this time, I set the animation of the two-handed giant sword through the mod [attack, run, Walk, crawl, etc.], and finally set the hand-held two-handed giant sword as the triggering event of the animation.
If it can't be realized, I won't be disappointed, because this mod is really awesome!

**Comment by iwoplaza** [comment]
Hey! I discuss the support for other-mod animations in this issue #234.
