### ISSUE TITLE
Wierd armor

### ISSUE THREAD

**Issue by JustMarq-I** [iwoplaza/MoBends#233]
Hello i am BUZZBEEHONEYCOMB, and i encountered a wierd bug. so the armor that i am wearing stays still while the animation leaves the armor behind which is wierd and sometimes the the head piece sinks into the head. please fix this!

**Comment by iwoplaza** [comment]
Which armor piece are you referring to? A vanilla armor? Or maybe a modded armor? Also, could you include screenshots.

**Comment by iwoplaza** [comment]
Closing the issue for the reason of insufficient details. If you have a specific example, and there are no other issues reporting that specific example, make sure to state which version of Minecraft you're using, which version of Mo' Bends you're using, and provide screenshots and a list of other mods.
