### ISSUE TITLE
Left Hand Sword Trails Not Oriented Correctly

### ISSUE THREAD

**Issue by Alphie-U** [iwoplaza/MoBends#252]
When you set your main hand in Minecraft to be your left hand, the sword trails for Patreon backers appear at a 90 degree angle misoriented to the orientation they're supposed to be. (See video below, please ignore the odd squish, was recorded on ultrawide monitor)

**Steps to reproduce the behavior:**
1. Press escape, go to Options... > Skin Customization...
2. Change "Main Hand" to "Left"
3. Enter third person view using your bound key
4. Slash with a sword

**Expected behavior:** 
The sword trail is oriented correctly

**Video**
https://user-images.githubusercontent.com/64037441/143689705-4b7e2387-d94a-4e0f-8f5b-fcf91bbe6a4c.mp4

**Context:**
 - Minecraft version: 1.12.2
 - Mo' Bends version: 1.1.0
 - Other installed mods: Optifine

**Additional context**
No bends packs or resource packs were enabled at the time this bug happened.

**Comment by iwoplaza** [comment]
Fixed in the upcoming update! 😄 
![left-hand-sword-trail](https://user-images.githubusercontent.com/7166752/146659174-dbdc74a1-73a7-42f2-bb01-5324a6ce0168.gif)
