### ISSUE TITLE
Bug (custom heads floating over mobs heads)

### ISSUE THREAD

**Issue by Paladin20038** [iwoplaza/MoBends#267]
So, I was playing a MMORPG server Wynncraft, but the custom heads were floating above mobs heads (see the picture), rather than being attached to their heads

Expected mobs to have their heads **attached**

**Screenshots**
https://imgur.com/a/OQZEZxU

 - Minecraft version: [1.12.2]
 - Mo' Bends version [0.24]
 - Other installed mods [Optifine, Wynntils, BetterAnimals]

**Comment by iwoplaza** [comment]
This is a bug report for an old version of Mo' Bends, please use the new (at the time of writing, 1.2.1 version) ❤️
