### ISSUE TITLE
Animating Custom Bipeds? [Mod Compat Minecolonies]

### ISSUE THREAD

**Issue by SulpherStaer** [iwoplaza/MoBends#39]
Hey there!

I really enjoy this mod, but how do I add entities from other mods to the list? They use the basic biped anim, so animating them as zombies / players should be possible.

How do I do this? The mod in question is Minecolonies.

https://github.com/ldtteam/minecolonies

Here is the bit where they render the citizens. Maybe that helps you tell me how to add them.
https://github.com/ldtteam/minecolonies/blob/a349e0ee5b29e4c056072de1e4c300130437d1a5/src/main/java/com/minecolonies/coremod/client/render/RenderBipedCitizen.java#L21

**Comment by iwoplaza** [comment]
This will be possible with the new addon system I'm adding to Mo' Bends. You'll have to wait for the upcoming 1.0.0 version 🙂.
