### ISSUE TITLE
Wearable backpacks issue.

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [iwoplaza/MoBends#41]
Hey there!
I love your mod guys!
Could you add compatibility with wearable backpacks?
Basically after installing the mod the backpack is invisible when you wear it.
https://minecraft.curseforge.com/projects/wearable-backpacks
![2018-12-03_01 16 14](https://user-images.githubusercontent.com/34427698/49346891-ee672880-f698-11e8-84d4-f62305675a2f.png)
![2018-12-03_01 16 19](https://user-images.githubusercontent.com/34427698/49346894-f7f09080-f698-11e8-8355-cf619e3b11f9.png)

**Comment by iwoplaza** [comment]
I worked directly with the WearableBackpacks people, and we sorted the issue out on both sides, so whenever Mo' Bends 1.0.0 comes out, it will be fixed 😄
