### ISSUE TITLE
compatibility problem with ice and fire

### ISSUE THREAD

**Issue by zkdev** [iwoplaza/MoBends#42]
Ice and fire armors are kinda messed up with mo bends :/

![1](https://user-images.githubusercontent.com/43617695/49697753-72e70900-fbbb-11e8-9b42-b02789b50b61.PNG)

**Comment by NovaLynxie** [comment]
I have noticed the same visual glitch as well. This is with dragon armor blue.
![2019-02-08_20 07 16](https://user-images.githubusercontent.com/21307676/52504296-f040f100-2bdf-11e9-9a50-8a81ded8ffbb.png)

**Comment by brykkiller** [comment]
The same problem. Are the authors going to fix it ?

**Comment by iwoplaza** [comment]
Which version of the mod is this?

**Comment by NovaLynxie** [comment]
I believe I used the latest version v0.24 for 1.12.2 from the curseforge page. The date stamp on that is old since it's from 2017.

**Comment by zkdev** [comment]
> Which version of the mod is this?

this one: https://drive.google.com/open?id=1LVjCIjMwsz9yP5ojQXDSOPUeyBQ_LJNw
guess its 1.5.2

**Comment by zai205** [comment]
I'm having this problem to

**Comment by iwoplaza** [comment]
This is fixed, and will be released with the upcoming BETA-3 update. Thanks for the report and help with finding the issues! <3
