### ISSUE TITLE
Slim armor model, player skin, more player models and gender mod glitch

### ISSUE THREAD

**Issue by ghost** [iwoplaza/MoBends#45]
Chestplate, pants and boots are not attached to the player slim model and the skin is not displaying correctly.
![2019-01-08_14 26 14](https://user-images.githubusercontent.com/46331070/50847268-4bb95e00-1358-11e9-815e-145740b30527.png)
![2019-01-08_14 26 10](https://user-images.githubusercontent.com/46331070/50847270-4c51f480-1358-11e9-81ab-2acbb1859c26.png)

While MorePlayerModels have strange breasts by default the Gender mod renders breasts only in the last GitHub version but have an issue.
MorePlayerModels breasts
![2019-01-08_12 58 09](https://user-images.githubusercontent.com/46331070/50847269-4c51f480-1358-11e9-8f22-61301a7565a7.png)
Gender mod
Yay! ![2019-01-08_16 04 40](https://user-images.githubusercontent.com/46331070/50850041-ea958880-135f-11e9-9459-9d276294cf66.png)
Oops! ![2019-01-08_16 06 02](https://user-images.githubusercontent.com/46331070/50850040-ea958880-135f-11e9-9bea-a849169264fe.png)

Skin not rendering correctly without MorePlayerModels and Gender mod:
![2019-01-08_15 31 10](https://user-images.githubusercontent.com/46331070/50848125-7f958300-135a-11e9-93ea-90b79ca1fa4f.png)

**Comment by iwoplaza** [comment]
Which Mo' Bends version is this?
