### ISSUE TITLE
visual glitch: skulls worn by skeletons and zombies (and their variants)

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [iwoplaza/MoBends#48]
![2019-02-05_19 46 09a p yd](https://user-images.githubusercontent.com/6912435/52451781-fd89ad00-2b05-11e9-9e3b-af0addbcaabf.png)
The skulls hover above the mob's head.
Additionally, the pitch of the skull seems to be inverted relative to the head (though I could be wrong)

**Comment by iwoplaza** [comment]
This has been fixed in the unreleased snapshots 🙂. Thanks for the report.
