### ISSUE TITLE
[Question] Model animating

### ISSUE THREAD

**Issue by wojtek2kdev** [iwoplaza/MoBends#56]
Hi, Do you use some tool for fast creating and export model with animations? Mainly I'm lookin for something that allows me to create and export animations code, cuz I don't wanna write it for my own blindly, without any graphical representation.

**Comment by iwoplaza** [comment]
Hello 🙂. All my animations until the upcoming version 1.0.0 were all written by me in code. I didn't really use any animation software, I just wrote some code and saw if I liked it, if not, I changed the code and tried again. The upcoming version though will be equiped with an animation editor, and I'm looking to create an animation format that would ease users with creating their own animations for the mod 😄. There is also an option to create the animations in Blender, then export them using a custom plugin, but that's for a later date.

I'm sure there are plenty APIs out there that could help you out in adding keyframe animations to your mod.

**Comment by crispytwig** [comment]
I'd suggest Blockbench.
