### ISSUE TITLE
"Compatibility mode" Is far from compatible (More Player Models)

### ISSUE THREAD

**Issue by Delta0199** [iwoplaza/MoBends#6]
Opening the More Player Models menu and going to "Config" on the bottom right-hand corner
![screen shot 2018-06-27 at 11 25 45 am](https://user-images.githubusercontent.com/40637697/41983854-2ec5f820-79fd-11e8-8c13-dbd16d248f6e.png)
It opens a menu, by clicking on "Compatibility mode", and toggling it to "Yes"
![screen shot 2018-06-27 at 11 26 00 am](https://user-images.githubusercontent.com/40637697/41983894-4830ff76-79fd-11e8-8c0e-c14b86aa59cb.png)
![screen shot 2018-06-27 at 11 26 15 am](https://user-images.githubusercontent.com/40637697/41983939-62a0bcf2-79fd-11e8-8018-5fec4432ed3f.png)
It causes the original player model to render for your skin, but all of the armor follows the mo'bends animations
![2018-06-27_11 27 02](https://user-images.githubusercontent.com/40637697/41984085-c5647fd6-79fd-11e8-8ddb-af9b67f3cdc9.png)
Toggling it back off does not alleviate the problem, the only currently known solution is to remove the .cfg file from the config folder

**Comment by iwoplaza** [comment]
Does it work when you turn it off, and restart the game?

**Comment by Delta0199** [comment]
No, turning it on and off again does not fix the problem

**Comment by iwoplaza** [comment]
I've found 2 ways to alleviate the problem:
1. Go into the Mo' Bends menu ('G' by default) -> Customize -> Player, and clicking on the portrait of the player twice, to turn in off and on. This will bring back the animations to the original model.
2. Press F10 (the refresh button)

**Comment by Delta0199** [comment]
oh no, not the refresh button

**Comment by Delta0199** [comment]
thank you anyway

**Comment by LUGJIA** [comment]
Hey It Seems like juassicraft has a issue with this player model mod to any help?

**Comment by ghost** [comment]
Try "epic fight mod" as it takes priority to render itself and has a lot of the animated movements in mo bends, plus it has a whole epic fighting system by pressing r. Still, while rendering it, the whole model from mpm will be reset to the default "epic fight mod" model until you activate it again. At least both models won't be integrated weirdly into the Minecraft model at the same time. 😟
