### ISSUE TITLE
Thaumcraft and other 3D armor models/textures

### ISSUE THREAD

**Issue by GogoZBg** [iwoplaza/MoBends#65]
Just like with other mods like Draconic Evoulution, armor sets with 3D parts don't render corectly.
Resulting in no 3d parts and messy texture soup on the top of the player
Screenshot of thaumcraft armor:
![image](https://user-images.githubusercontent.com/50183674/57040543-63e71d00-6c68-11e9-873b-cefe0dbb0ef2.png)

I hope you can one day this will be fixed. No rushing tho! 👍

**Comment by Dradonis** [comment]
Have the same thing with Ice and Fire armor and angel ring wings look as if you have wings growing out of your ass

**Comment by iwoplaza** [comment]
This has been addressed, the fix for this will be rolled out with the upcoming BETA-3 release. Thanks for the report!
