### ISSUE TITLE
Player walking animation messed up at large distances (floating point precision errors)

### ISSUE THREAD

**Issue by muzikbike** [iwoplaza/MoBends#77]
When very far from the world origin on any axis, player animations get weird and twitchy. Very easy to see with mods such as https://github.com/ThisTestUser/FarLandsMod but can still be seen within vanilla bounds.

![2019-08-27_21 45 42](https://user-images.githubusercontent.com/52297970/63806784-470bdf00-c914-11e9-931d-12e57bcf9361.png)

1. Create a default superflat world

2. /tp 20000000 10 20000000

3. Walk diagonally

**Comment by iwoplaza** [comment]
This has been fixed in the upcoming 1.0.0 version due to a switch to using double precision floating point numbers. Thanks for the report!
