### ISSUE TITLE
Skin Overlay Bug

### ISSUE THREAD

**Issue by ghost** [iwoplaza/MoBends#87]
I looked in third person on my legs and the overlay was not around my legs as usual.

![2019-12-31_17 42 30 Edit](https://user-images.githubusercontent.com/59396688/71627826-2ec70c00-2bf5-11ea-95f4-e5e56c635283.png)

![2019-12-31_17 42 37](https://user-images.githubusercontent.com/59396688/71627848-4d2d0780-2bf5-11ea-838a-a246c15a6ea7.png)

**Comment by iwoplaza** [comment]
This shouldn't happen anymore on the latest snapshot release :D.
