### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ghost** [iwoplaza/MoBends#88]
the game crashed after a little while and the world, I was playing on, is not loading anymore (game crashing again)

error: The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0

![mobends_crash](https://user-images.githubusercontent.com/59396688/71627898-8c5b5880-2bf5-11ea-9d1e-b0e68770d508.PNG)

**Comment by iwoplaza** [comment]
ChunkNibbleArrays? Is that for certain related to Mo' Bends? What other mods do you have installed?

**Comment by ghost** [comment]
only mobends

**Comment by iwoplaza** [comment]
I think this happens often when switching Minecraft versions, there are apparently ways to fix this: https://shockbyte.com/billing/knowledgebase/110/javalangIllegalArgumentException-ChunkNibbleArrays-should-be-2048-bytes-not-0.html.

This seems to have nothing to do with Mo' Bends though.
