### ISSUE TITLE
More of a request for compatibility

### ISSUE THREAD

**Issue by Jennifercutixx** [iwoplaza/MoBends#92]
Playing with mo bends mod istalled is amazing just that the compatibility with Construct's Armory and other mods is unfortunate. Because when mo bends and Construct's armory is together it makes it so the amor is invisable and unable to see whats in ur hand with the armor on. And to be honest it would be nice if mo bends can support armor mods so you can see the armor which is on your player. Or that the vinilla mo bends setting on ur player could make it so u can see your armor with armor mods.

I hope you have the time and effeort to do a support for this. Because i know making mods and doing support for them takes quite a while. But i hope you can make mo bends supportive of other mods to be able to work together.

**Comment by iwoplaza** [comment]
Hey! Thank you for the report. Let's continue our discussion about this here #196
