### ISSUE TITLE
Player model's arms twisted around in the inventory screen

### ISSUE THREAD

**Issue by Rynex21** [iwoplaza/MoBends#95]
I'm noticed player's arm are bent and twisted toward left side while holding torches in the inventory screen.
When I am holding torch with Main hand.
![2020-03-26_00 25 59](https://user-images.githubusercontent.com/62661766/77561246-680fcf00-6ef9-11ea-948f-38bdaea19d03.png)
and with Offhand.
![2020-03-26_00 26 05](https://user-images.githubusercontent.com/62661766/77561345-8bd31500-6ef9-11ea-9bb0-9acdbcd2ac91.png)

**Comment by Rynex21** [comment]
I didn't test this with no mods though..

**Comment by CarvedCreeper** [comment]
Have you tried turning on third person, and opening the inventory?

**Comment by Rynex21** [comment]
Ok,I have tried both of third person views just now and it's still happened.
Also I have tried this with no mods but still persists.

**Comment by Krosta8** [comment]
To add something, here is a GIF about it https://imgur.com/a/UkAvrHm
You just need to have something in your off hand, open and close inventory.

**Comment by iwoplaza** [comment]
Thanks for the report! For cleanliness, referring to the other issue of the same nature #221.
This has been addressed, and a fix for this will get rolled out in the upcoming BETA-3 update.
